# Generated by Django 6.1.1 on 2026-09-25 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_profile_sms_limit'),
        ('api', '0123_alter_channel_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flip',
            name='reason',
            field=models.CharField(choices=[('', 'Unknown'), ('timeout', 'Timeout'), ('fail', 'Fail signal'), ('maintenance', 'Maintenance window')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('tz', models.CharField(default='UTC', max_length=50)),
                ('all_checks', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checks', models.ManyToManyField(blank=True, to='api.check')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
            ],
            options={
                'ordering': ['-starts'],
            },
        ),
    ]
